import os

def generate_report(site_res):
    """
    Generates a professional executive report (Markdown format).
    """
    address_str = site_res.get('address', 'Exact Coordinates Specified')
    report_content = f"""# Executive Site Selection Briefing
## Target: {address_str} ({site_res['latitude']}, {site_res['longitude']})
---

### 🏆 Overall Score: {site_res['feasibility_score']:.1f}/100

### 🚀 Physics & Efficiency (Elon Musk)
- **Local Ambient Temp**: {site_res.get('ambient_temp_c', 'N/A')}°C
- **PUE Prediction**: {site_res['predicted_pue']:.2f}
- **Power Capacity**: {site_res['power_capacity_mw']:.1f} MW
- **Assessment**: {site_res['rationale'].split('. ')[0]}

### 💰 Financials & Moat (Warren Buffett)
- **Grid Stability**: {site_res['grid_stability']*100:.0f}%
- **Assessment**: {site_res['rationale'].split('. ')[1]}

### 🌍 Infrastructure Strategy (Bill Gates)
- **Sustainability Aspect**: Included in score
- **Assessment**: {site_res['rationale'].split('. ')[2]}

### 🎨 Design & Connectivity (Steve Jobs)
- **Strategic Mapping**: High-Fidelity
- **Assessment**: {site_res['rationale'].split('. ')[3]}

---
### 📋 Technical Metadata
- **Zoning**: {site_res['zoning_type']}
- **Permit Status**: {site_res['permit_status']}

**Disclaimer**: This report was generated by the Multi-Agent Site Selection Supervisor.
"""
    
    report_path = f"report_{site_res['latitude']}_{site_res['longitude']}.md"
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_content)
    
    print(f"✅ Executive report generated at {report_path}")
    return report_path
